### ISSUE TITLE
[BUG] Smithy Service name must be defined ahead of time

### ISSUE THREAD

**Issue by codypenta** [aws/aws-pdk#176]
### Describe the bug

When you generate a sample project, then manually overwrite the smithy sample generated. `npx projen` will not rebuild the smithy model.

### Expected Behavior

Able to overwrite the generated smithy model file and rebuild to get new types.

### Current Behavior

`npx projen` will not recognize input change and will not build out new model

### Reproduction Steps

1.) generate smithy open api
2.) manually change namespace, service, and operations
3.) Run `npx projen`

### Possible Solution

This was fixed by deleted the generated API, then typing the service name ahead of time:

```ts
const api = new SmithyApiGatewayTsProject({
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  defaultReleaseBranch: "main",
  name: "api",
  parent: monorepo,
  outdir: "packages/api",
  serviceName: "aws.bumpercars#Bumpercars", <-- add this, then npx projen
  deps: [
    "@aws-lambda-powertools/logger",
    "@aws-lambda-powertools/tracer",
    "@aws-lambda-powertools/metrics",
  ],
});
```

### PDK version used

0.11.3

### Environment details (OS name and version, etc.)

MacOS

**Comment by cogwirrel** [comment]
Thanks for raising this!

This is an interesting one, as the `main.smithy` file is generated as a "sample file" - ie it's generated once but after that is never re-generated since it is intended just as sample code. We wouldn't want to overwrite anything that has been edited by a user already.

I suppose an option to partially address this might be to check whether the `main.smithy` that exists in the filesystem is still the same "hello world" example. This might help with that edge case, but I worry that this would actually make it less clear overall since it might give users a false sense that the namespace and service name will be updated even after editing the smithy model.

Perhaps the best answer would be to improve the documentation here: https://github.com/aws/aws-prototyping-sdk/blob/mainline/packages/open-api-gateway/src/project/types.ts#L38-L41 ? We could mention there that changes to the service name after generation won't be reflected in the model after regeneration?

**Comment by cogwirrel** [comment]
Chatted with @agdimech on this - given that users will always end up picking their own `serviceName` - we'll make this parameter required - that way at least it's less likely that users will generate with the wrong name and have to regenerate later.

We'll also ensure the documentation is clear that the smithy model won't be regenerated with the new service name unless you delete it.
