### ISSUE TITLE
[BUG] NX Monorepo errors with @types/babel__traverse

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-pdk#227]
### Describe the bug

Linking the description and resolution for the bug from projen as I ran into this and they helped debug it.

https://github.com/projen/projen/issues/2264

### Expected Behavior

No errors during compile.

### Current Behavior

```
� compile | jsii --silence-warnings=reserved-word
[2022-11-29T17:24:08.213] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
../../../node_modules/@types/babel__traverse/index.d.ts:68:50 - error TS1005: ']' expected.

68 export type ArrayKeys<T> = keyof { [P in keyof T as T[P] extends any[] ? P : never]: P };
                                                    ~~
../../../node_modules/@types/babel__traverse/index.d.ts:68:53 - error TS1005: ';' expected.

68 export type ArrayKeys<T> = keyof { [P in keyof T as T[P] extends any[] ? P : never]: P };
                                                       ~
```

### Reproduction Steps

npm run compile

### Possible Solution

Pinning @types/babel__traverse to 7.18.2

### PDK version used

0.12.20

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Linux x86_64

**Comment by agdimech** [comment]
Hi. Thanks for raising this.

The PDK itself is currently being built using `@types/babel__traverse@7.17.1` on NX and I don't see any build failures surfacing. Are you able to please provide more details into how this can be reproduced? A sample repo which I can trigger a build on would be ideal.

**Comment by pchaganti** [comment]
The link in the projen ticket above contains a zipped test repo.

thanks

**Comment by pchaganti** [comment]
Attached a test repo. node modules removed for size reasons.

    Run yarn install
    Run npx nx run-many --target=build --all

[test_projen.zip](https://github.com/aws/aws-prototyping-sdk/files/10132690/test_projen.zip)

**Comment by agdimech** [comment]
As a stopgap, are you able to do the following:

1. Add this on line 14/15 after your monorepo definition in .projenrc.ts `project.package.addPackageResolutions("@types/babel__traverse@7.18.2");`
2. Run `npx projen` from root
3. `Run npx nx run-many --target=build --all`

The issue appears to be that v >= 7.18.3 do not support typescript 3.9 (JSII limitation) and hence it will need to be pinned.

Also as an aside, make sure your .projenrc.ts file only has a single call to `project.synth()` otherwise you will be wasting a lot of time unnecessarily waiting for things to synthesize :)

I will add a follow-up fix to `NXMonorepoProject` to automatically Pin this dep to 7.18.2.

**Comment by pchaganti** [comment]
I am already doing the stopgap and it works for me.
