### ISSUE TITLE
[BUG] support lookups for CDK Graph resources defined outside of stack

### ISSUE THREAD

**Issue by Andrchiamus** [aws/aws-pdk#271]
### Describe the bug

When trying to use CdkGraph on a stack that references a Lambda external to current stack (i.e.  Function.fromName() ) it errors out.

### Expected Behavior

For lookups to be handled and resources defined outside of stack to be displayed in diagram.

### Current Behavior

Throws error
```
Error: LogicalId defined outside of stack: ...
```

### Reproduction Steps

Include a lambda function from lookup in stack to be graphed.

### PDK version used

0.13.0

### Environment details (OS name and version, etc.)

macOS 12.6.1

**Comment by JeremyJonas** [comment]
Hi @Andrchiamus, thanks for reporting this issue and good catch. Will need to add some test coverage for this case and find proper way to handle.

If you are interested in contributing that would be great, if not I will try to resolve by next week. Cheers!

**Comment by JeremyJonas** [comment]
@Andrchiamus can you provide more repro steps, and confirm that your "external Lambda" is in fact outside of any stacks.

Given that resources can not be created outside of stack, not sure if you are referencing to something else or have an edge case - https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/core/lib/stack.ts#L185-L188

I have tested with an "external lambda" and "external bucket" (imports), but nested as children of a stack and it works without error. The diagram that it generates does not show icon graphics for these imports, which makes sense since they don't define "cfnType" details. But can work on that.

Please share your code example of how you structured your app, stacks, and external lambda instantiation. Cheers.

**Comment by JeremyJonas** [comment]
Hi @Andrchiamus, are you still experience this issue? Please provide more details so we can reproduce, otherwise we will close the issue as stale. Thank you.
