### ISSUE TITLE
[BUG] .npmrc is generated in all the packages

### ISSUE THREAD

**Issue by rverma-dev** [aws/aws-pdk#376]
### Describe the bug

With version 0.17.3 onward, projen is also generating .npmrc file in each directory based on https://github.com/sperka/aws-prototyping-sdk/blob/c85312c706e776ef49beed02fa97df3285759cf8/private/projects/pdk-monorepo-project.ts#L174

This lead to unnecessary file generation and warnings
```
npm WARN ignoring workspace config at /Users/rverma/dev/aws/nsa/packages/demo/.npmrc 
```
More details of handling this is here https://github.com/npm/cli/issues/4605

### Expected Behavior

To generate only file in the root package

### Current Behavior

Generating npmrc in all the packages

### Reproduction Steps

Add a child project to monorepo and observe

### PDK version used

0.17.3/4

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Macos ARM

**Comment by cogwirrel** [comment]
This is actually due to a change I made to projen to always create a `.npmrc` file for PNPM projects so that `resolution-mode` is set to `highest`. For reference see the projen issue here https://github.com/projen/projen/issues/2628 and where I upgraded the projen peer dependency version in PDK here: https://github.com/aws/aws-prototyping-sdk/pull/373

Nevertheless it is annoying having the extra `.npmrc` files, so I'll send a PR to remove any subproject `.npmrc` files if you're using the `nx-monorepo`
