### ISSUE TITLE
[FEATURE] (type-safe-api) enable input parameter for `model.options.smithy.smithyBuildOptions.maven` dependency versions

### ISSUE THREAD

**Issue by sperka** [aws/aws-pdk#377]
### Describe the feature

This feature would enable the end user to control the versions of default `requiredDependencies` that are being added to default `gradle` file.

### Use Case

When adding a new dependency as a project consumer (e.g.: `software.amazon.smithy:smithy-aws-apigateway-traits`) I want to make sure that all dependency versions are the same - otherwise I may run into errors.

* Sticking to built-in `TypeSafeApi` version would be an option, but there is no exposed field to pick the supplied version number - if it changes in future versions, it won't get reflected on the user's code.
* Using my own version for every dependency works but if there are any future updates in the _list_ of default dependencies in `TypeSafeApiProject` will also result in mixed-version dependencies

### Proposed Solution

Add an optional `requiredSmithyDependencyVersion` into `SmithyMavenConfiguration`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

0.17.4

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS 13.2.1

**Comment by cogwirrel** [comment]
Hey! Thanks for raising this! :) You can actually achieve the desired behaviour already by specifying the required dependencies yourself with your desired version, since user-specified dependencies take precedence over the built in ones. For example:

```ts
new TypeSafeApiProject({
  ...
  model: {
    language: ModelLanguage.SMITHY,
    options: {
      smithy: {
        serviceName: {
          namespace: 'my.service',
          serviceName: 'MyService',
        },
        smithyBuildOptions: {
          maven: {
            dependencies: [
              "software.amazon.smithy:smithy-cli:1.28.1",
              "software.amazon.smithy:smithy-model:1.28.1",
              "software.amazon.smithy:smithy-openapi:1.28.1",
              "software.amazon.smithy:smithy-aws-traits:1.28.1",
            ]
          }
        }
      }
    },
  },
});
```

Documentation here:

https://github.com/aws/aws-prototyping-sdk/blob/db1741c2f29f6f53e81754b2f013c24b00720bb9/packages/type-safe-api/src/project/model/smithy/types.ts#L80-L90

Looking at the above this is out of date though as we use 1.28.0 by default! :)

And implementation:

https://github.com/aws/aws-prototyping-sdk/blob/db1741c2f29f6f53e81754b2f013c24b00720bb9/packages/type-safe-api/src/project/model/smithy/smithy-definition.ts#L99-L122

I think it might become a bit more confusing if there were another parameter for specifying the required dependency version :)

**Comment by sperka** [comment]
ok. I skipped L109/L110 in `smithy-definitions.ts` and thought there's a merge between user supplied dependencies and built-in ones, hence the confusion about potential dependency mix-up.

this case, I'm closing this issue.
