### ISSUE TITLE
[TypeSafe-API] Adopt Middy as the runtime interceptor framework

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-pdk#520]
### Describe the feature

Rather than having custom IDL for the runtime interceptors, it would be great to use [middy](https://middy.js.org/) which has lots of middleware and powertools integration out-of-the-box, plus is already used heavily in the community.

Also supports python with https://github.com/apasare/pymiddy, not sure if other languages have adopted.

### Use Case

Prevent users from having to learn another IDL for middleware pattern and gain benefit of the middy middleware already available.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

*

### Environment details (OS name and version, etc.)

*

**Comment by cogwirrel** [comment]
I've not used Middy before, it looks cool!

Given that Middy can wrap a lambda handler, you can already use it with `type-safe-api` instead of/alongside the "native" interceptors without any changes to the framework. It'd just be like:

```ts
const sayHello = sayHelloHandler(async ({ input }) => {
  return {
    statusCode: 200,
    body: {
      message: `Hello ${input.requestParameters.name}`,
    },
  };
});

export const handler = middy(sayHello)
  .use(...) // Could use the ready-made middleware like @middy/http-cors here
  .use(...);
```

You could even use it with the handler router, eg:

```ts
const router = handlerRouter({ ... });

export const handler = middy(router).use(...);
```

Middy also seems to be generic enough to also support usage with the typed handlers by wrapping those prior to passing to the generated handler wrappers. So if you still wanted to use middy but also write middleware in terms of the typed inputs/outputs (like the native interceptors) you could do something like:

```ts
import middy from '@middy/core';
import {
  ChainedRequestInput,
  OperationResponse,
  SayHelloChainedHandlerFunction,
  sayHelloHandler
} from "t-api-typescript-runtime";

// Some middy middleware written generically in terms of typed inputs/outputs
// This could also be typed specifically to sayHello inputs/outputs
const myMiddleware = <RequestParameters, RequestArrayParameters, RequestBody, Response>(): middy.MiddlewareObj<ChainedRequestInput<
  RequestParameters,
  RequestArrayParameters,
  RequestBody,
  Response
>, Response | OperationResponse<500, { errorMessage: string }>> => {
  type Input = ChainedRequestInput<
    RequestParameters,
    RequestArrayParameters,
    RequestBody,
    Response
  >;
  type Output = Response | OperationResponse<500, { errorMessage: string }>;

  const before: middy.MiddlewareFn<Input, Output> = async (request): Promise<void> => {
    // We can access request.input which is our typed input
    console.log('Request Before', request);
  };

  const after: middy.MiddlewareFn<Input, Output> = async (request): Promise<void> => {
    // We can access request.response which has the response before it was serialised (ie request.response.body is an object)
    console.log('Request After', request);
  };

  return {
    before,
    after,
  };
};

// Define the handler in terms of typed inputs/outputs separately
const sayHello: SayHelloChainedHandlerFunction = async ({ input }) => {
  return {
    statusCode: 200,
    body: {
      message: `Hello ${input.requestParameters.name}`,
    },
  };
};

// Wrap the typed handler in middy and use the middy middleware in terms of typed inputs/outputs
// NB: Middy's return type isn't compatible with the sayHelloHandler input type so we need to coerce it here
export const handler = sayHelloHandler(middy(sayHello).use(myMiddleware()) as SayHelloChainedHandlerFunction);
```

So I'm not sure there's really anything that'd need to change in `type-safe-api`, other than adding some documentation on "How to use Middy" :) (I suppose this response could be that documentation!).

I'd be reluctant to remove the "native" interceptors as we at least have a fairly consistent interface for all 3 supported languages, and I'm not sure if there's a Middy available for Java.
