### ISSUE TITLE
[BUG] Website example only allows access from specific countries

### ISSUE THREAD

**Issue by falnyr** [aws/aws-pdk#598]
### Describe the bug

When deploying the infrastructure project for a static website, visiting the provided URL fails with an error:

> The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

### Expected Behavior

The example code should not limit the access to a specific country.

### Current Behavior

Currently, the CloudFront distribution is configured to only allow traffic from these countries:
"AU",
"ID",
"IN",
"JP",
"KR",
"SG",
"US"

### Reproduction Steps

Follow the deployment steps in [1. Your first AWS CDK Project](https://aws.github.io/aws-pdk/getting_started/your_first_aws_pdk_project.html).

### Possible Solution

Remove the country allowlist restriction

### PDK version used

0.22.13

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS Sonoma, Node 18.14

**Comment by agdimech** [comment]
Hi - the best practice with Cloudfront distributions is to enable Geo restrictions (this is actually enforced within the PDK Nag and AWS Solutions nag packs).

The list you provided above is just a default set which is generated as part of the sample code after which point it is completely configurable.

There are two options at this point:

1.) Modify the list to allow the required countries to the list.
2.) If you do not wish to enable geo-restriction, that would be more of an exception and as such would require you to not only remove the geoRestriction props from the `StaticWebsite` construct but would also require adding a Nag suppression in order to make the build pass.

Feel free to re-open this issue if you feel it was closed in error.

**Comment by falnyr** [comment]
Hey @agdimech,

It's important what sort of user experience do you want to go for. As it stands at the moment, following the basic deployment instructions, only the people from countries listed above get a result without having to manually fix the application. 

It can also be confusing for some people why did only these specific countries made the default list but not the likes of e.g.  countries of EU, Canada "CA" or New Zealand "NZ".

I suggest either increasing the default list to include a wide range of countries or make the country list a mandatory parameter in `CloudscapeReactTsWebsiteProject`.

**Comment by cogwirrel** [comment]
FYI the default allow-list has been removed in this PR: https://github.com/aws/aws-pdk/pull/747
